services:
  web:
    build: .
    command: ["uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

  db:
    image: docker.arvancloud.ir/postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: docker.arvancloud.ir/redis:7.2.4
    restart: always
  nginx:
    image: docker.arvancloud.ir/nginx:1.25.5
    restart: always
    ports:
      - "80:80"
